# Options for analysis running.
run:
  # Timeout for analysis
  timeout: 5m

linters:
  # Disable all linters.
  disable-all: true
  # Enable specific linter
  enable:
    # go vet
    - govet
    # res.body close
    - bodyclose
    # Report unused functions and variables
    - deadcode
    # Report when error return value is not acknowledged
    - errcheck
    # Check that error types are compared with errors.Is, that %w is used for wrapping error types in fmt.Errorf, and that errors.As is used to convert error types
    - errorlint
    # Check exhaustiveness of enum switch statements
    - exhaustive
    # Checks for pointers to enclosing loop variables
    - exportloopref
    # Finds forced type assertions
    - forcetypeassert
    # Gofumpt checks whether code was gofumpt-ed
    - gofumpt
    # Goimports does everything that gofmt does. Additionally it checks unused imports
    - goimports
    # An analyzer to detect magic numbers
    - gomnd
    # Inspects source code for security problems
    - gosec
    # It will give you some patterns of code that you don't need
    - gosimple
    # Checks that your code uses short syntax for if-statements whenever possible
    - ifshort
    # Report where unnecessary substitutions are made
    - ineffassign
    # Reports long lines
    - lll
    # Finds commonly misspelled English words in comments
    - misspell
    # Find code that shadows one of Go's predeclared identifiers
    - predeclared
    # Force them to write a reason when nolint
    - nolintlint
    # Checks that sql.Rows and sql.Stmt are closed
    - sqlclosecheck
    # Staticcheck is a go vet on steroids, applying a ton of static analysis checks
    - staticcheck
    # Report unused fields
    - structcheck
    # Stylecheck is a replacement for golint
    - stylecheck
    # Check if compilation passes
    - typecheck
    # Reports unused function parameters
    - unparam
    # Report unused variables, constants, functions, types, etc
    - unused
    # Report unused global variables and constants
    - varcheck
    # Tool for detection of leading and trailing whitespace
    - whitespace
    # Checks that errors returned from external packages are wrapped
    - wrapcheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  include:
    - EXC0012
    - EXC0013
    - EXC0014
  exclude-rules:
    - path: _test\.go
      linters:
        - wrapcheck
    - path: magefiles/
      linters:
        - deadcode

linters-settings:
  gofumpt:
    extra-rules: true
  goimports:
    local-prefixes: github.com/otimistas/gwork-server
  govet:
    enable-all: true
  stylecheck:
    checks:
      - all
      - -ST1000
