services:
  app:
    container_name: gwork-app
    build:
      context: .
      dockerfile: sample-container/Dockerfile
    environment:
      PORT: 50051
      DB_HOST: db
      DB_CONNECTION: pgsql
      DB_PORT: 5432
      DB_NAME: gwork
      DB_USERNAME: postgres
      DB_PASSWORD: password
      APP_DEBUG: true
      APP_ENV: development
      DB_URL: postgres://postgres:password@db:5432/gwork?sslmode=disable # For Dockerfile
    volumes:
      - .:/app:ro,cached
    ports:
      - 50051:50051
    working_dir: /app
    command: go run main.go # TODO: Change to the command for hot reloading
    depends_on:
      - db
  db:
    container_name: gwork-db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=gwork
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
