CREATE TABLE t_user_group (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id TEXT REFERENCES m_users(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    group_id TEXT REFERENCES m_groups(id) ON UPDATE CASCADE ON DELETE CASCADE NOT NULL,
    is_valid BOOLEAN NOT NULL DEFAULT 1,
    added_at TIMESTAMP NOT NULL
);
