name: Build

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-server:
    name: Build server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - name: Download go modules
        run: go mod download
      - name: Build go
        env:
          CGO_ENABLED: 0
        run: go build -o /tmp/app main.go
  build-docker:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build image
        run: docker image build -t app .
