name: Lint

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint-go:
    name: Lint go files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          check-latest: true
      - name: Download go modules
        run: go mod download
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.20.0
          policy_allow: true
      - name: Lint go files
        run: golangci-lint run
  lint-docker:
    name: Lint dockerfiles
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.20.0
          policy_allow: true
      - name: Lint app dockerfile
        run: hadolint Dockerfile
      - name: Lint dev container dockerfile
        run: hadolint .devcontainer/Dockerfile
  lint-workflows:
    name: Lint github workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.20.0
          policy_allow: true
      - name: Ensure that shellcheck is installed
        run: shellcheck --version
      - name: Lint github workflows
        run: actionlint
  check-aqua-checksum:
    name: Check aqua checksum
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup aqua
        uses: aquaproj/aqua-installer@v2.2.0
        with:
          aqua_version: v2.20.0
          policy_allow: true
      - name: Update aqua checksum
        run: aqua update-checksum --prune
      - name: Check diff
        run: git diff --exit-code aqua-checksums.json
